---
- name: nmap scan
  hosts: all
  gather_facts: no

  tasks:
    - name: Targets
      include_tasks: 
        content:
          - name: "Print target"
            debug:
              msg: "Target: {{ item }}"

          - name: "Run scan"
            command: "nmap -sT -sV {{ item }}"
            register: nmap_res
            changed_when: false

          - name: "Print report"
            debug:
              msg: "Scan output: {{ echo_res.stdout }}"
      loop: "{{ targets }}"
