---
- name: nmap scan
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Scan each target
      ansible.builtin.include_tasks: nmap_scan_target.yml
      loop: "{{ targets }}"
      loop_control:
        loop_var: target
